config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :characters
end

app/models/ac_calculator.rb
class ACCalculator
  def initialize(character)
    @character = character
  end


  def calculate_ac
    if character.shield
      base_ac + 2
    else
      base_ac
    end
  end

  def armored?
    character.armor.present?
  end

  def base_ac
    if armored?
      self.send("#{character.armor}_ac")
    else
      10 + character.dex_mod
    end
  end

  def leather_armor_ac
    11 + character.dex_mod
  end

  def chain_shirt_ac
    13 + max_dex(2)
  end

  def plate_mail_ac
    18
  end

  def max_dex(max)
    if character.dex_mod >= max
      max
    else
      character.dex_mod
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ActiveRecord::Base
  STR = "str"
  CON = "con"
  DEX = "dex"
  WIS = "wis"
  INT = "int"
  CHA = "cha"

  STATS = [
    STR,
    CON,
    DEX,
    WIS,
    INT,
    CHA,
  ]

  has_many :mods, inverse_of: :character
  has_many :levels, inverse_of: :character
  accepts_nested_attributes_for :levels, :mods

  def regenerate!
    static_mods.destroy_all
    case race
    when"Human"
      hash = JSON.parse(File.read("#{Rails.root}/data/human.json"))
      apply(hash)
    end

    levels.each do |l|
      case l.class_name
      when"Fighter"
        hash = JSON.parse(File.read("#{Rails.root}/data/fighter.json"))
        apply(hash[l.number.to_s])
      end
    end
  end

  def apply(hash)
    hash["mods"].each do |m| 
      digest_mod mod: m, 
        source: hash["source"]
    end
  end

  def remove(hash)
    hash["mods"].each do |m| 
      remove_mod mod: m, 
        source: hash["source"]
    end
  end

  STATS.each do |stat|
    define_method stat do
      numeric_value_for stat
    end

    define_method "#{stat}=" do |arg|
      mods.where(
        modifier: stat, 
        source: Mod::BASE_STAT
      ).first_or_initialize.tap do |mod|
        mod.value = arg 
        mod.memo = "Base Stat"
        mod.save!
      end
    end

    define_method "#{stat}_mod" do
      (send(stat) - 10) / 2
    end
  end

  def ac
    ACCalculator.new(self).calculate_ac
  end

  def proficiency_bonus
    numeric_value_for "proficiency_bonus"
  end

  def armor_proficiencies
    mods_for "armor_proficiency"
  end

  def weapon_proficiencies
    mods_for "weapon_proficiency"
  end

  def languages
    mods_for "language"
  end

  def armor
    mods_for("armor").first
  end

  def shield
    mods_for("shield").first
  end

  private

  def remove_mod(mod:, source:)
    mod = Mod.find_by(
      source: source,
      character: self,
      value: mod["value"],
      memo: mod["memo"],
      modifier: mod["modifier"],
      description: mod["description"]
    )
    mod.destroy if mod.present?
  end

  def digest_mod(mod:, source:)
    Mod.create(
      source: source,
      character: self,
      value: mod["value"],
      memo: mod["memo"],
      modifier: mod["modifier"],
      description: mod["description"]
    )
  end

  def numeric_value_for(modifier)
    mods_for(modifier).
      pluck(:value).
      map(&:to_i).
      inject(:+)
  end

  def static_mods
    mods.where(dynamic: false)
  end

  def mods_for(modifier)
    mods.where(modifier: modifier)
  end
end

app/models/level.rb
class Level < ActiveRecord::Base
  belongs_to :character, inverse_of: :levels
  validates :number, presence: true
  validates :class_name, presence: true
end

app/models/mod.rb
class Mod < ActiveRecord::Base
  BASE_STAT = "Base Stat Roll"
  CLASS_FEAURE = "Class Feature"
  RACIAL_TRAIT = "Racial Trait" 

  ALLOWED_SOURCES = [
    BASE_STAT,
    CLASS_FEAURE,
    RACIAL_TRAIT
  ].freeze

  belongs_to :character, inverse_of: :mods

  validates :source, inclusion: { in: ALLOWED_SOURCES }, presence: true
  validates :modifier, presence: true
  validates :value, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def new
    @character = Character.create
    redirect_to edit_character_path(@character, step: "race")
  end

  def edit
    @character = Character.find(params[:id])
    @character.levels.build
    @character.mods.build
    @step = params[:step]
  end

  def update
    @character = Character.find(params[:id])
    @character.update_attributes(character_params)
    if next_step == "foo"
      byebug
    end
    redirect_to edit_character_path(@character, step: next_step)
  end

  private

  def character_params
    params.require(:character).permit(
      :race, 
      levels_attributes: [ :class_name, :number ],
      mods_attributes: [ :source, :modifier, :value ]
    )
  end

  def next_step
    params[:step] || params[:character][:next_step]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/characters/edit.haml
#character-creation-container
  =render "characters/steps/#{@step}"

app/views/characters/steps/_class.haml
%h1 Choose A Class!

= form_for @character do |f|
  = f.fields_for :levels do |lf|
    = lf.radio_button :class_name, 'Fighter'
    = label :class_name_Fighter, "Fighter"
    = lf.hidden_field :number, value: 1
  = f.hidden_field :next_step, value: "stats"
  = f.submit

app/views/characters/steps/_race.haml
%h1 Choose A Race!

= form_for @character do |f|
  = f.radio_button :race, 'Human'
  = label :race_Human, "Human"
  = f.hidden_field :next_step, value: "class"
  = f.submit

app/views/characters/steps/_stats.haml
%h1 Choose A Class!

= form_for @character do |f|
  = f.fields_for :mods do |mf|
    = mf.label "Strength"
    = mf.number_field :value
    = mf.hidden_field :modifier, value: 'str'
    = mf.hidden_field "source", value: Mod::BASE_STAT
    = mf.hidden_field "dynamic", value: false
  = f.fields_for :mods do |mf|
    = mf.label "Dexterity"
    = mf.number_field :value
    = mf.hidden_field :modifier, value: 'dex'
    = mf.hidden_field "source", value: Mod::BASE_STAT
    = mf.hidden_field "dynamic", value: false
  = f.fields_for :mods do |mf|
    = mf.label "Constitution"
    = mf.number_field :value
    = mf.hidden_field :modifier, value: 'cha'
    = mf.hidden_field "source", value: Mod::BASE_STAT
    = mf.hidden_field "dynamic", value: false
  = f.fields_for :mods do |mf|
    = mf.label "Wisdom"
    = mf.number_field :value
    = mf.hidden_field :modifier, value: 'wis'
    = mf.hidden_field "source", value: Mod::BASE_STAT
    = mf.hidden_field "dynamic", value: false
  = f.fields_for :mods do |mf|
    = mf.label "Intelligence"
    = mf.number_field :value
    = mf.hidden_field :modifier, value: 'int'
    = mf.hidden_field "source", value: Mod::BASE_STAT
    = mf.hidden_field "dynamic", value: false
  = f.fields_for :mods do |mf|
    = mf.label "Charisma"
    = mf.number_field :value
    = mf.hidden_field :modifier, value: 'cha'
    = mf.hidden_field "source", value: Mod::BASE_STAT
    = mf.hidden_field "dynamic", value: false
  = f.hidden_field :next_step, value: "foo"
  = f.submit

app/views/home/index.haml
%h1 Hello!

=link_to "Create A Character",  new_character_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrithubCore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>